---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nodejs
  labels:
    app: test-nodejs
  annotations:
    nethopper.io/tag-edge: 'true'
spec:
  selector:
    matchLabels:
      app: test-nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: test-nodejs
    spec:
      containers:
        - name: frontend
          image: nethopper/test-nodejs:latest
          ports:
            - containerPort: 9080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler