apiVersion: v1
kind: Service
metadata:
  name: nhtestv1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
  selector:
    app: nhtestv1
