apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: ''
    namespace: nethopper
    server: 'https://kubernetes.default.svc'
  source:
    path: sync-waves
    repoURL: 'https://github.com/nethopper2/argocd-example-apps.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
